### ISSUE TITLE
iOS 8 Support

### ISSUE THREAD

**Issue by iCyberon** [Athlee/OnboardingKit#1]
Hey @Mozharovsky, can you use TZStackView instead of UIStackView to support iOS 8 as well?

**Comment by mozharovsky** [comment]
Hey @iCyberon, people use iOS 8 more rarely than iOS 9 this is why we based on the latter with its handy features. Anyway, if you find older versions' support necessary we'll definitely include it in the next version. Please let me know. 👍

**Comment by iCyberon** [comment]
@Mozharovsky You're absolutely right, but according to our stats almost 6.5% are using iOS 8. That's really not a very small percentage of users. I can create a PR if you need.

**Comment by mozharovsky** [comment]
@iCyberon PRs are highly appreciated, thank you for being interested in helping! ✋

**Comment by mozharovsky** [comment]
Solved in #2, thank you @iCyberon. :)

**Comment by iCyberon** [comment]
Can you publish a new version to cocoapods?

**Comment by mozharovsky** [comment]
Yes, it'll be updated within an hour. :)

**Comment by mozharovsky** [comment]
@iCyberon we're live on v0.0.3 now. Thank you for your support! 
Also we have further plans on improving this library, check it out in a few days, hopefully, you'll find them useful. ✌️
